### ISSUE TITLE
Generate types for modules

### ISSUE THREAD

**Issue by Lock128** [nioc/netatmo-nodejs-api#1]
Hi

is there a chance to generate/includes types for the modules?

Thanks
Johannes

**Comment by nioc** [comment]
Hello. Yes, I can add a type files within 1 or 2 weeks

**Comment by Lock128** [comment]
..and make it usable in node18/node20? ;)

**Comment by nioc** [comment]
It is actually usable with recent node versions (on my laptop, using node 20, it works).
What do you mean?

**Comment by nioc** [comment]
🚀 version 2.0.0.
Let me know if you see type errors.
